CREATE DATABASE practicaAW;
USE practicaAW;

CREATE TABLE users (
    ID INT(11) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(80) NOT NULL
);

ALTER TABLE users ADD PRIMARY KEY (ID);
ALTER TABLE users MODIFY username VARCHAR(50) NOT NULL UNIQUE;
ALTER TABLE users MODIFY ID INT(11) NOT NULL AUTO_INCREMENT;
